language: ruby
ruby:
  - 2.6
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
  - bundle install
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
